<?php
declare(strict_types=1);
namespace App\Services;
use App\Core\Database;use App\Core\Request;
class ChargeCategoryService{
 private function school():int{return(int)(Request::get('auth_user',[])['school_id']??0);}private function text(array$d,string$k):?string{$v=trim((string)($d[$k]??''));return$v?:null;}
 public function all(bool$active=false):array{$q='SELECT * FROM charge_categories WHERE school_id=?'.($active?' AND status="ACTIVE"':'').' ORDER BY label';$s=Database::connect()->prepare($q);$s->execute([$this->school()]);return$s->fetchAll();}
 public function one(int$id):array|false{$s=Database::connect()->prepare('SELECT * FROM charge_categories WHERE id=? AND school_id=?');$s->execute([$id,$this->school()]);return$s->fetch()?:false;}
 public function save(array$d,?int$id=null):array{$school=$this->school();if(!$school)return['error'=>'Établissement introuvable'];$label=$this->text($d,'label');$code=strtoupper((string)preg_replace('/[^A-Z0-9_]/','_',strtoupper($this->text($d,'code')??'')));$period=(string)($d['periodicity']??'ONE_TIME');$amount=array_key_exists('default_amount',$d)&&$d['default_amount']!==''?round((float)$d['default_amount'],2):null;if(!$label||!$code)return['error'=>'Le libellé et le code sont obligatoires'];if(!in_array($period,['MONTHLY','ANNUAL','ONE_TIME','SELECTED_MONTHS','CUSTOM'],true)||($amount!==null&&$amount<0))return['error'=>'Catégorie invalide'];$pdo=Database::connect();try{if($id){if(!$this->one($id))return['error'=>'Catégorie introuvable','status'=>404];$pdo->prepare('UPDATE charge_categories SET code=?,label=?,description=?,default_amount=?,periodicity=?,status=? WHERE id=? AND school_id=?')->execute([$code,$label,$this->text($d,'description'),$amount,$period,in_array($d['status']??'ACTIVE',['ACTIVE','ARCHIVED'],true)?$d['status']:'ACTIVE',$id,$school]);return['id'=>$id];}$pdo->prepare('INSERT INTO charge_categories(school_id,code,label,description,default_amount,periodicity)VALUES(?,?,?,?,?,?)')->execute([$school,$code,$label,$this->text($d,'description'),$amount,$period]);return['id'=>(int)$pdo->lastInsertId()];}catch(\PDOException){return['error'=>'Ce code de catégorie existe déjà'];}}
 public function archive(int$id):array{$c=$this->one($id);if(!$c)return['error'=>'Catégorie introuvable','status'=>404];Database::connect()->prepare('UPDATE charge_categories SET status="ARCHIVED" WHERE id=? AND school_id=?')->execute([$id,$this->school()]);return['id'=>$id,'status'=>'ARCHIVED'];}
}
