<?php
declare(strict_types=1);
namespace App\Services;
use App\Core\Database; use App\Core\Request; use PDO;

class DiscountService {
 private function school():int{return(int)(Request::get('auth_user',[])['school_id']??0);} private function user():?int{$v=Request::get('auth_user',[])['id']??null;return$v?(int)$v:null;} private function m(mixed$v):float{return round((float)$v+0.0000001,2);}
 private function ids(array$v):array{return array_values(array_unique(array_filter(array_map('intval',$v))));}
 private function validIds(string$table,array$ids):bool{if(!$ids)return false;$in=implode(',',array_fill(0,count($ids),'?'));$q=Database::connect()->prepare("SELECT id FROM $table WHERE school_id=? AND id IN ($in)");$q->execute([$this->school(),...$ids]);return count($q->fetchAll())===count($ids);}
 private function validate(array$d):array { $type=(string)($d['discount_type']??'');$value=$this->m($d['discount_value']??-1);$reason=trim((string)($d['reason']??''));$students=$this->ids((array)($d['student_ids']??[]));$categories=$this->ids((array)($d['category_ids']??[]));if(!in_array($type,['PERCENTAGE','FIXED'],true)||$value<0||($type==='PERCENTAGE'&&$value>100)||$reason===''||!$this->validIds('students',$students)||($categories&&!$this->validIds('charge_categories',$categories)))return['error'=>'Réduction ou bénéficiaires invalides'];if(!empty($d['family_id'])){$q=Database::connect()->prepare('SELECT id FROM families WHERE id=? AND school_id=?');$q->execute([(int)$d['family_id'],$this->school()]);if(!$q->fetch())return['error'=>'Famille invalide'];$q=Database::connect()->prepare('SELECT COUNT(*) FROM students WHERE school_id=? AND family_id=? AND id IN ('.implode(',',array_fill(0,count($students),'?')).')');$q->execute([$this->school(),(int)$d['family_id'],...$students]);if((int)$q->fetchColumn()!==count($students))return['error'=>'Les enfants sélectionnés ne correspondent pas à cette famille'];}foreach(['starts_on','ends_on']as$k)if(!empty($d[$k])&&!preg_match('/^\d{4}-\d{2}-\d{2}$/',(string)$d[$k]))return['error'=>'Date de réduction invalide'];if(!empty($d['ends_on'])&&!empty($d['starts_on'])&&$d['ends_on']<$d['starts_on'])return['error'=>'La date de fin doit être postérieure à la date de début'];return compact('type','value','reason','students','categories'); }
 private function candidates(array$d):array { $v=$this->validate($d);if(isset($v['error']))return$v;$where=['fi.school_id=?','fi.student_id IN ('.implode(',',array_fill(0,count($v['students']),'?')).')','fi.status IN ("UNPAID","PARTIAL")'];$p=[$this->school(),...$v['students']];if($v['categories']){$where[]='d.charge_category_id IN ('.implode(',',array_fill(0,count($v['categories']),'?')).')';array_push($p,...$v['categories']);}if(!empty($d['charge_ids'])){$chargeIds=$this->ids((array)$d['charge_ids']);if(!$chargeIds)return['error'=>'Charges invalides'];$where[]='fi.id IN ('.implode(',',array_fill(0,count($chargeIds),'?')).')';array_push($p,...$chargeIds);}if(isset($d['billing_month'])&&$d['billing_month']!==''){$where[]='d.billing_month=?';$p[]=(int)$d['billing_month'];}if(!empty($d['months'])){$months=$this->ids((array)$d['months']);$where[]='d.billing_month IN ('.implode(',',array_fill(0,count($months),'?')).')';array_push($p,...$months);}if(!empty($d['year_value'])){$where[]='d.year_value=?';$p[]=(int)$d['year_value'];}$sql='SELECT fi.id,fi.student_id,fi.paid_amount,fi.status,d.charge_category_id,d.original_amount,d.discount_type,d.discount_value,d.final_amount FROM student_financial_items fi JOIN student_financial_item_details d ON d.student_financial_item_id=fi.id WHERE '.implode(' AND ',$where);$q=Database::connect()->prepare($sql);$q->execute($p);return['validation'=>$v,'charges'=>$q->fetchAll()]; }
 private function history(PDO$p,int$id,string$action,?array$b,?array$a,string$reason):void{$p->prepare('INSERT INTO student_financial_item_history(school_id,student_financial_item_id,action,before_data,after_data,reason,changed_by)VALUES(?,?,?,?,?,?,?)')->execute([$this->school(),$id,$action,$b?json_encode($b):null,$a?json_encode($a):null,$reason,$this->user()]);}
 public function all():array{$q=Database::connect()->prepare('SELECT d.*,COUNT(t.id) target_count FROM charge_discounts d LEFT JOIN charge_discount_targets t ON t.discount_id=d.id WHERE d.school_id=? GROUP BY d.id ORDER BY d.id DESC');$q->execute([$this->school()]);return$q->fetchAll();}
 public function one(int$id):array|false{$p=Database::connect();$q=$p->prepare('SELECT * FROM charge_discounts WHERE id=? AND school_id=?');$q->execute([$id,$this->school()]);$row=$q->fetch();if(!$row)return false;$t=$p->prepare('SELECT t.student_id,t.charge_category_id,s.first_name,s.last_name,c.label AS category_label FROM charge_discount_targets t JOIN students s ON s.id=t.student_id LEFT JOIN charge_categories c ON c.id=t.charge_category_id WHERE t.discount_id=?');$t->execute([$id]);$row['targets']=$t->fetchAll();return$row;}
 public function preview(array$d):array{$c=$this->candidates($d);if(isset($c['error']))return$c;$lines=[];$conflicts=[];foreach($c['charges']as$r){$amount=$this->m($r['original_amount']);$removed=$c['validation']['type']==='PERCENTAGE'?$this->m($amount*$c['validation']['value']/100):$c['validation']['value'];if($removed>$amount)return['error'=>'La réduction ne peut pas dépasser le montant initial'];$line=['charge_id'=>(int)$r['id'],'initial_amount'=>$amount,'discount_amount'=>$removed,'final_amount'=>$this->m($amount-$removed),'existing_discount'=>$r['discount_type']?['type'=>$r['discount_type'],'value'=>$r['discount_value']]:null];$lines[]=$line;if($r['discount_type'])$conflicts[]=$line;}return['charges'=>$lines,'conflicts'=>$conflicts,'total'=>$this->m(array_sum(array_column($lines,'final_amount')))];}
public function create(array$d):array{$candidate=$this->candidates($d);if(isset($candidate['error']))return$candidate;$preview=$this->preview($d);if(isset($preview['error']))return$preview;if(!$candidate['charges'])return['error'=>'Aucune charge éligible à cette réduction'];if($preview['conflicts']&&!($d['replace_existing']??false))return['error'=>'Une réduction active existe déjà','status'=>409,'conflicts'=>$preview['conflicts']];$v=$candidate['validation'];$p=Database::connect();$ownsTransaction=!$p->inTransaction();if($ownsTransaction)$p->beginTransaction();try{$p->prepare('INSERT INTO charge_discounts(school_id,discount_type,discount_value,reason,starts_on,ends_on,created_by)VALUES(?,?,?,?,?,?,?)')->execute([$this->school(),$v['type'],$v['value'],$v['reason'],$d['starts_on']??null,$d['ends_on']??null,$this->user()]);$id=(int)$p->lastInsertId();foreach($v['students']as$s){$cats=$v['categories']?:[null];foreach($cats as$cat)$p->prepare('INSERT INTO charge_discount_targets(discount_id,student_id,charge_category_id)VALUES(?,?,?)')->execute([$id,$s,$cat]);}foreach($preview['charges']as$line){$matches=array_values(array_filter($candidate['charges'],fn($r)=>(int)$r['id']===$line['charge_id']));$old=$matches[0]??[];if(($old['discount_type']??null)){$p->prepare('UPDATE charge_discounts SET status="REPLACED",replaced_by=? WHERE school_id=? AND id<>? AND id IN (SELECT discount_id FROM charge_discount_targets WHERE student_id=?) AND status="ACTIVE"')->execute([$id,$this->school(),$id,$old['student_id']]);}$p->prepare('UPDATE student_financial_item_details SET discount_type=?,discount_value=?,final_amount=?,modified_by=? WHERE student_financial_item_id=? AND school_id=?')->execute([$v['type'],$v['value'],$line['final_amount'],$this->user(),$line['charge_id'],$this->school()]);$p->prepare('UPDATE student_financial_items SET discount_amount=?,total_amount=?,status=CASE WHEN paid_amount>=? THEN "PAID" WHEN paid_amount>0 THEN "PARTIAL" ELSE "UNPAID" END WHERE id=? AND school_id=?')->execute([$line['discount_amount'],$line['final_amount'],$line['final_amount'],$line['charge_id'],$this->school()]);$this->history($p,$line['charge_id'],'DISCOUNT_APPLIED',$old,['discount_id'=>$id,'final_amount'=>$line['final_amount']],$v['reason']);}if($ownsTransaction)$p->commit();return['id'=>$id,'applied_charges'=>count($preview['charges'])];}catch(\Throwable$e){if($ownsTransaction&&$p->inTransaction())$p->rollBack();return['error'=>$e->getMessage()];}}
 public function cancel(int$id,array$d=[]):array{$old=$this->one($id);if(!$old)return['error'=>'Réduction introuvable','status'=>404];if($old['status']!=='ACTIVE')return['error'=>'Cette réduction n’est plus active','status'=>409];$p=Database::connect();$p->prepare('UPDATE charge_discounts SET status="CANCELLED",cancellation_reason=? WHERE id=? AND school_id=?')->execute([trim((string)($d['reason']??''))?:null,$id,$this->school()]);return['id'=>$id,'status'=>'CANCELLED'];}
 public function replace(int$id,array$d):array{$old=$this->one($id);if(!$old)return['error'=>'Réduction introuvable','status'=>404];$d['replace_existing']=true;if(empty($d['student_ids']))$d['student_ids']=array_values(array_unique(array_column($old['targets'],'student_id')));if(empty($d['category_ids']))$d['category_ids']=array_values(array_unique(array_filter(array_column($old['targets'],'charge_category_id'))));$r=$this->create($d);if(isset($r['error']))return$r;Database::connect()->prepare('UPDATE charge_discounts SET status="REPLACED",replaced_by=? WHERE id=? AND school_id=?')->execute([$r['id'],$id,$this->school()]);return$r+['replaced_discount_id'=>$id];}
 public function historyFor(int$id):array{$d=$this->one($id);if(!$d)return[];$q=Database::connect()->prepare('SELECT h.* FROM student_financial_item_history h WHERE h.school_id=? AND JSON_SEARCH(h.after_data,"one",CAST(? AS CHAR)) IS NOT NULL ORDER BY h.id DESC');$q->execute([$this->school(),$id]);return$q->fetchAll();}
}
