<?php
declare(strict_types=1);
namespace App\Services;
use App\Core\Database;
use App\Core\Request;
use Dompdf\Dompdf;
use Dompdf\Options;
class StudentDocumentService {
 public function generate(array $d):array{$u=Request::get('auth_user',[]);$school=(int)($u['school_id']??0);if(!$school)return ['error'=>'School is required'];$ids=array_values(array_filter(array_map('intval',$d['student_ids']??[])));if(!$ids)return ['error'=>'Select at least one student'];$in=implode(',',array_fill(0,count($ids),'?'));$pdo=Database::connect();$s=$pdo->prepare("SELECT s.internal_number,s.massar_code,s.first_name,s.last_name,s.class_name,s.monthly_amount,COALESCE(SUM(mf.amount_paid),0) paid,COALESCE(SUM(mf.remaining_amount),0) remaining FROM students s LEFT JOIN monthly_fees mf ON mf.student_id=s.id AND mf.school_id=s.school_id WHERE s.school_id=? AND s.id IN ($in) GROUP BY s.id ORDER BY s.last_name");$s->execute([$school,...$ids]);$rows=$s->fetchAll();if(count($rows)!==count($ids))return ['error'=>'Invalid student selection'];$e=static fn($v)=>htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');$css='@page{margin:9mm 10mm}body{font-family:DejaVu Sans;font-size:8.5px;color:#111}.school-document-header{width:100%;border-collapse:collapse;border-bottom:.5px solid #555;margin-bottom:5px}.school-document-header td{border:0;padding:0 0 3px}.school-document-header .school-logo{width:39px}.school-document-header strong{font-size:11px}.school-document-header span{font-size:7.5px}h2{text-align:center;font-size:12px;margin:4px 0 2px}p{margin:0 0 4px}table{width:100%;border-collapse:collapse;margin:4px 0}th,td{border:.4px solid #777;padding:2.5px 3px;text-align:left}th{background:#fff}.total{font-weight:bold;border-top:.5px solid #555}';$html='<!doctype html><html><head><meta charset="UTF-8"><style>'.$css.'</style></head><body>'.(new SchoolDocumentHeaderService())->render($school).'<h2>Situation financière élèves</h2><p>Référence : DOC-'.date('YmdHis').' · Généré le '.date('d/m/Y H:i').'</p><table><tr><th>Matricule</th><th>Massar</th><th>Élève</th><th>Classe</th><th>Mensualité</th><th>Payé</th><th>Reste</th></tr>';$total=0;foreach($rows as $r){$total+=(float)$r['remaining'];$html.='<tr><td>'.$e($r['internal_number']??'').'</td><td>'.$e($r['massar_code']??'').'</td><td>'.$e($r['last_name'].' '.$r['first_name']).'</td><td>'.$e($r['class_name']??'').'</td><td>'.number_format((float)$r['monthly_amount'],2,',',' ').' DH</td><td>'.number_format((float)$r['paid'],2,',',' ').' DH</td><td>'.number_format((float)$r['remaining'],2,',',' ').' DH</td></tr>';}$html.='<tr class="total"><th colspan="6">Total général</th><th>'.number_format($total,2,',',' ').' DH</th></tr></table><table style="margin-top:9px"><tr><td style="border:0;width:50%">Signature direction</td><td style="border:0">Cachet établissement</td></tr></table></body></html>';$o=new Options();$o->set('defaultFont','DejaVu Sans');$pdf=new Dompdf($o);$pdf->loadHtml($html);$pdf->setPaper('A4','portrait');$pdf->render();return ['content'=>$pdf->output(),'filename'=>'situation-eleves-'.date('YmdHis').'.pdf'];}
}
