<?php
declare(strict_types=1);
namespace App\Services;
use App\Core\Database;
use App\Core\Request;
use Dompdf\Dompdf;
use Dompdf\Options;
class StudentDocumentService {
 public function generate(array $d):array{$u=Request::get('auth_user',[]);$school=(int)($u['school_id']??0);if(!$school)return ['error'=>'School is required'];$ids=array_values(array_filter(array_map('intval',$d['student_ids']??[])));if(!$ids)return ['error'=>'Select at least one student'];$in=implode(',',array_fill(0,count($ids),'?'));$pdo=Database::connect();$s=$pdo->prepare("SELECT s.internal_number,s.massar_code,s.first_name,s.last_name,s.class_name,s.monthly_amount,COALESCE(SUM(mf.amount_paid),0) paid,COALESCE(SUM(mf.remaining_amount),0) remaining FROM students s LEFT JOIN monthly_fees mf ON mf.student_id=s.id AND mf.school_id=s.school_id WHERE s.school_id=? AND s.id IN ($in) GROUP BY s.id ORDER BY s.last_name");$s->execute([$school,...$ids]);$rows=$s->fetchAll();if(count($rows)!==count($ids))return ['error'=>'Invalid student selection'];$schoolInfo=$pdo->prepare('SELECT name,address,phone,logo_path FROM schools WHERE id=?');$schoolInfo->execute([$school]);$info=$schoolInfo->fetch();$html='<h1>'.htmlspecialchars($info['name']).'</h1><p>'.htmlspecialchars($info['address']??'').' · '.htmlspecialchars($info['phone']??'').'</p><h2>Situation financière élèves</h2><p>Référence : DOC-'.date('YmdHis').' · Généré le '.date('d/m/Y H:i').'</p><table width="100%" border="1" cellspacing="0" cellpadding="6"><tr><th>Matricule</th><th>Massar</th><th>Élève</th><th>Classe</th><th>Mensualité</th><th>Payé</th><th>Reste</th></tr>';$total=0;foreach($rows as $r){$total+=(float)$r['remaining'];$html.='<tr><td>'.htmlspecialchars($r['internal_number']??'').'</td><td>'.htmlspecialchars($r['massar_code']??'').'</td><td>'.htmlspecialchars($r['last_name'].' '.$r['first_name']).'</td><td>'.htmlspecialchars($r['class_name']??'').'</td><td>'.$r['monthly_amount'].'</td><td>'.$r['paid'].'</td><td>'.$r['remaining'].'</td></tr>';}$html.='<tr><th colspan="6">Total général</th><th>'.$total.'</th></tr></table><br><br><table width="100%"><tr><td>Signature responsable</td><td>Cachet direction</td></tr></table>';$o=new Options();$o->set('defaultFont','DejaVu Sans');$pdf=new Dompdf($o);$pdf->loadHtml($html);$pdf->setPaper('A4',($d['orientation']??'portrait')==='landscape'?'landscape':'portrait');$pdf->render();return ['content'=>$pdf->output(),'filename'=>'situation-eleves-'.date('YmdHis').'.pdf'];}
}
