import { useEffect, useMemo, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { getClassLevels } from "../services/classLevelService";
import { createStudent, getStudentById, updateStudent } from "../services/studentService";
import { getActiveAcademicYear, getChargeCategories } from "../services/studentFinanceService";

const guardian = () => ({ full_name:"", phone_primary:"", phone_secondary:"", email:"", relationship_type:"Responsable" });
const charge = () => ({ charge_category_id:"", label:"", original_amount:"", discount_type:"", discount_value:"", due_date:"" });
const blank = { first_name:"",last_name:"",first_name_ar:"",last_name_ar:"",date_of_birth:"",gender:"",address:"",class_level_id:"",class_name:"",status:"REGISTERED",internal_number:"",massar_code:"",cne:"",parent_name:"Responsable",parent_phone:"N/A",monthly_amount:0,discount_percent:0,uses_transport:false,guardians:[guardian()],charges:[] };
const total = c => { const a=Number(c.original_amount||0), v=Number(c.discount_value||0), d=c.discount_type==="PERCENTAGE"?a*v/100:c.discount_type==="FIXED"?v:0; return {a,d,f:Math.max(0,a-d)}; };
const money = n => `${new Intl.NumberFormat("fr-MA",{minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(n||0))} DH`;

export default function StudentFormPage(){
 const {id}=useParams(), editing=Boolean(id), navigate=useNavigate(); const [form,setForm]=useState(blank),[levels,setLevels]=useState([]),[categories,setCategories]=useState([]),[year,setYear]=useState(null),[error,setError]=useState(""),[saving,setSaving]=useState(false);
 useEffect(()=>{let ok=true;(async()=>{try{const [l,c,a,d]=await Promise.all([getClassLevels(),getChargeCategories(),getActiveAcademicYear(),editing?getStudentById(id):Promise.resolve(null)]);if(!ok)return;setLevels(l||[]);setCategories((c||[]).filter(x=>x.status==="ACTIVE"));setYear(a?.active_academic_year);if(d){const s=d.student||d;setForm(f=>({...f,...s,class_level_id:String(s.class_level_id||""),parent_phone:d.parent?.phone||s.phone||"N/A",guardians:d.guardians?.length?d.guardians.map(x=>({...guardian(),...x})):f.guardians,charges:(d.charges||[]).map(x=>({...x,charge_category_id:String(x.charge_category_id||""),original_amount:x.original_amount||x.total_amount,discount_value:x.discount_value||""}))}));}}catch{setError("Impossible de charger le dossier.")}})();return()=>{ok=false}},[id,editing]);
 const set=(k,v)=>setForm(x=>({...x,[k]:v})); const setGuardian=(i,k,v)=>setForm(x=>({...x,guardians:x.guardians.map((g,n)=>n===i?{...g,[k]:v}:g)})); const setCharge=(i,k,v)=>setForm(x=>({...x,charges:x.charges.map((c,n)=>n===i?{...c,[k]:v}:c)}));
 const transport=categories.find(x=>x.code==="TRANSPORT"); const setTransport=yes=>setForm(x=>{const rest=x.charges.filter(c=>!c.transport);return {...x,uses_transport:yes,charges:yes?[...rest,{...charge(),transport:true,charge_category_id:String(transport?.id||""),label:"Transport"}]:rest}});
 const summary=useMemo(()=>form.charges.reduce((r,c)=>{const x=total(c);return {a:r.a+x.a,d:r.d+x.d,f:r.f+x.f}},{a:0,d:0,f:0}),[form.charges]);
 const submit=async e=>{e.preventDefault();setError("");if(!year){setError("Aucune année scolaire active.");return}for(const c of form.charges){const x=total(c);if(!c.charge_category_id||x.a<0||x.d<0||x.f<0||(c.discount_type==="PERCENTAGE"&&Number(c.discount_value)>100)){setError("Vérifiez les frais et réductions.");return}}setSaving(true);try{const guardians=form.guardians.filter(g=>g.full_name.trim());const main=guardians[0];const payload={...form,modern_profile:true,school_year:null,parent_name:main?.full_name||form.parent_name,parent_phone:main?.phone_primary||form.parent_phone,guardians,charges:form.charges.filter(c=>!c.id).map(c=>({...c,original_amount:Number(c.original_amount||0),discount_value:Number(c.discount_value||0)}))};const r=editing?await updateStudent(id,payload):await createStudent(payload);navigate(`/students/${r.id||id}`)}catch(e){setError(e.response?.data?.message||"Enregistrement impossible.")}finally{setSaving(false)}};
 return <div className="admin-grid student-form-page"><section className="panel panel-header"><div><h2>{editing?"Modifier l’élève":"Ajouter un élève"}</h2><p className="muted">Dossier scolaire, responsables et frais.</p></div><Link className="secondary-btn button-link" to="/students">Retour</Link></section><form className="admin-grid" onSubmit={submit}>
 <section className="panel student-form-section"><h3>1. Informations élève</h3><div className="student-form-grid">{[["first_name","Prénom"],["last_name","Nom"],["first_name_ar","Prénom arabe"],["last_name_ar","Nom arabe"],["internal_number","Matricule"],["massar_code","Code Massar"],["cne","CNE"]].map(([k,l])=><label key={k}>{l}<input required={k==="first_name"||k==="last_name"} dir={k.endsWith("_ar")?"rtl":undefined} value={form[k]||""} onChange={e=>set(k,e.target.value)}/></label>)}<label>Date de naissance<input type="date" value={form.date_of_birth||""} onChange={e=>set("date_of_birth",e.target.value)}/></label><label>Sexe<select value={form.gender||""} onChange={e=>set("gender",e.target.value)}><option value="">—</option><option value="F">Féminin</option><option value="M">Masculin</option></select></label><label>Statut<select value={form.status} onChange={e=>set("status",e.target.value)}>{["PRE_REGISTERED","REGISTERED","WAITING_LIST","CANCELLED","ARCHIVED"].map(x=><option key={x}>{x}</option>)}</select></label><label className="student-form-full-field">Adresse<textarea value={form.address||""} onChange={e=>set("address",e.target.value)}/></label></div></section>
 <section className="panel student-form-section"><h3>2. Scolarité</h3><div className="student-form-grid"><label>Niveau<select required value={form.class_level_id} onChange={e=>set("class_level_id",e.target.value)}><option value="">Choisir</option>{levels.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Classe<input value={form.class_name||""} onChange={e=>set("class_name",e.target.value)}/></label><p><strong>Année active :</strong> {year?.name||"—"}</p></div></section>
 <section className="panel student-form-section"><h3>3. Responsable familial</h3>{form.guardians.map((g,i)=><div className="student-form-grid" key={i}><label>Nom complet<input required={i===0} value={g.full_name} onChange={e=>setGuardian(i,"full_name",e.target.value)}/></label><label>Téléphone<input required={i===0} value={g.phone_primary} onChange={e=>setGuardian(i,"phone_primary",e.target.value)}/></label><label>Téléphone secondaire<input value={g.phone_secondary} onChange={e=>setGuardian(i,"phone_secondary",e.target.value)}/></label><label>Email<input type="email" value={g.email} onChange={e=>setGuardian(i,"email",e.target.value)}/></label><label>Relation<input value={g.relationship_type} onChange={e=>setGuardian(i,"relationship_type",e.target.value)}/></label>{i>0&&<button type="button" className="secondary-btn" onClick={()=>setForm(x=>({...x,guardians:x.guardians.filter((_,n)=>n!==i)}))}>Retirer</button>}</div>)}{form.guardians.length<3&&<button type="button" className="secondary-btn" onClick={()=>setForm(x=>({...x,guardians:[...x.guardians,guardian()]}))}>+ Ajouter un responsable</button>}</section>
 <section className="panel student-form-section"><h3>4. Transport</h3><label><input type="radio" checked={!form.uses_transport} onChange={()=>setTransport(false)}/> Non</label><label><input type="radio" checked={!!form.uses_transport} onChange={()=>setTransport(true)}/> Oui</label>{form.uses_transport&&!transport&&<p className="error-text">Catégorie Transport indisponible.</p>}</section>
 <section className="panel student-form-section"><h3>5. Frais et réductions</h3>{form.charges.map((c,i)=>{const x=total(c);return <div className="student-form-grid" key={i}><label>Catégorie<select value={c.charge_category_id} onChange={e=>setCharge(i,"charge_category_id",e.target.value)}><option value="">Choisir</option>{categories.map(z=><option key={z.id} value={z.id}>{z.label}</option>)}</select></label><label>Libellé<input value={c.label||""} onChange={e=>setCharge(i,"label",e.target.value)}/></label><label>Montant<input type="number" min="0" step="0.01" value={c.original_amount} onChange={e=>setCharge(i,"original_amount",e.target.value)}/></label><label>Réduction<select value={c.discount_type||""} onChange={e=>setCharge(i,"discount_type",e.target.value)}><option value="">Aucune</option><option value="FIXED">Montant</option><option value="PERCENTAGE">Pourcentage</option></select></label><label>Valeur<input type="number" min="0" max={c.discount_type==="PERCENTAGE"?100:undefined} disabled={!c.discount_type} value={c.discount_value||""} onChange={e=>setCharge(i,"discount_value",e.target.value)}/></label><label>Échéance<input type="date" value={c.due_date||""} onChange={e=>setCharge(i,"due_date",e.target.value)}/></label><p><strong>Final : {money(x.f)}</strong>{c.id&&<small> Payé {money(c.paid_amount)} · Reste {money(c.remaining_amount)} · {c.status}</small>}</p>{!c.id&&<button type="button" className="secondary-btn" onClick={()=>setForm(x=>({...x,charges:x.charges.filter((_,n)=>n!==i)}))}>Supprimer</button>}</div>})}<button type="button" className="secondary-btn" onClick={()=>setForm(x=>({...x,charges:[...x.charges,charge()]}))}>+ Ajouter un frais</button><div className="student-net-fee"><strong>Résumé</strong><p>Total initial : {money(summary.a)}</p><p>Réductions : -{money(summary.d)}</p><p>Total à payer : {money(summary.f)}</p></div></section>
 <section className="panel student-form-footer">{error&&<p className="error-text">{error}</p>}<button disabled={saving}>{saving?"Enregistrement…":"Enregistrer"}</button></section></form></div>;
}
